subscribe:
  dump_path: '/usr/local/bin/pg_dump' # 命令路径
  historical: false  # 是否处理历史数据(一般用于第一次)
  db_host: '127.0.0.1'
  db_port: 5432
  db_name: 'asset_intel'
  db_user: 'itcp'
  db_pass: '123456'
  db_key: 'id'   # 表主键或者唯一id
  slot_name: 'slot_for_localhost'
  upstream: '127.0.0.1:50049'
  tables: # 订阅数据表，支持 ?* 通配符匹配
    - 'organization'
