# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/logical.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='proto/logical.proto',
    package='proto',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x13proto/logical.proto\x12\x05proto\"\x0e\n\x0cping_message\":\n\x0c\x63\x61ll_message\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0f\n\x07operate\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\"(\n\x05reply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x0eLogicalHandler\x12)\n\x04ping\x12\x13.proto.ping_message\x1a\x0c.proto.reply\x12)\n\x04\x63\x61ll\x12\x13.proto.call_message\x1a\x0c.proto.replyb\x06proto3'
)

_PING_MESSAGE = _descriptor.Descriptor(
    name='ping_message',
    full_name='proto.ping_message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=44,
)

_CALL_MESSAGE = _descriptor.Descriptor(
    name='call_message',
    full_name='proto.call_message',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='table', full_name='proto.call_message.table', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='operate', full_name='proto.call_message.operate', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='id', full_name='proto.call_message.id', index=2,
            number=3, type=3, cpp_type=2, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=46,
    serialized_end=104,
)

_REPLY = _descriptor.Descriptor(
    name='reply',
    full_name='proto.reply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='status', full_name='proto.reply.status', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='message', full_name='proto.reply.message', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=106,
    serialized_end=146,
)

DESCRIPTOR.message_types_by_name['ping_message'] = _PING_MESSAGE
DESCRIPTOR.message_types_by_name['call_message'] = _CALL_MESSAGE
DESCRIPTOR.message_types_by_name['reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ping_message = _reflection.GeneratedProtocolMessageType('ping_message', (_message.Message,), {
    'DESCRIPTOR': _PING_MESSAGE,
    '__module__': 'proto.logical_pb2'
    # @@protoc_insertion_point(class_scope:proto.ping_message)
})
_sym_db.RegisterMessage(ping_message)

call_message = _reflection.GeneratedProtocolMessageType('call_message', (_message.Message,), {
    'DESCRIPTOR': _CALL_MESSAGE,
    '__module__': 'proto.logical_pb2'
    # @@protoc_insertion_point(class_scope:proto.call_message)
})
_sym_db.RegisterMessage(call_message)

reply = _reflection.GeneratedProtocolMessageType('reply', (_message.Message,), {
    'DESCRIPTOR': _REPLY,
    '__module__': 'proto.logical_pb2'
    # @@protoc_insertion_point(class_scope:proto.reply)
})
_sym_db.RegisterMessage(reply)

_LOGICALHANDLER = _descriptor.ServiceDescriptor(
    name='LogicalHandler',
    full_name='proto.LogicalHandler',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=148,
    serialized_end=250,
    methods=[
        _descriptor.MethodDescriptor(
            name='ping',
            full_name='proto.LogicalHandler.ping',
            index=0,
            containing_service=None,
            input_type=_PING_MESSAGE,
            output_type=_REPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='call',
            full_name='proto.LogicalHandler.call',
            index=1,
            containing_service=None,
            input_type=_CALL_MESSAGE,
            output_type=_REPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_LOGICALHANDLER)

DESCRIPTOR.services_by_name['LogicalHandler'] = _LOGICALHANDLER

# @@protoc_insertion_point(module_scope)
